### ISSUE TITLE
效果不理想

### ISSUE THREAD

**Issue by nobody-ai2025** [JACKYLUO1991/DCBANet#1]
您好 ，我使用refuge数据集复现，但是结果相差了10个点左右，请问代码是不是还要做进一步修改才能达到您论文中的效果

**Comment by JACKYLUO1991** [comment]
@liu1037342030 你好，10个百分点有点差太多了，确保超参数和Paper一致吗？

**Comment by nobody-ai2025** [comment]
你好，一致的，我看论文的平衡参数λ为0.1  代码中的balance coefficient为0.01  请问这两个是一个参数吗  我按照你的代码来实现的 
只是调试了一下数据路径

**Comment by nobody-ai2025** [comment]
你好，在训练过程中，请问训练过程是要分两步骤进行的吗，先进行分割网络的训练，再
用对抗网络进行参数优化，还是只需一步训练就已经包含这两个步骤，训练得到的权重直接就可以使用。谢谢

**Comment by JACKYLUO1991** [comment]
@liu1037342030 是end-to-end的，并不是分步的,,,

**Comment by nobody-ai2025** [comment]
您好，您的代码在只添加了数据集路径其余都未进行修改的情况下进行训练和测试是否就可以了，超参数按照您代码中的默认即可，请问这样操作可以吗，非常感谢！

**Comment by JACKYLUO1991** [comment]
@liu1037342030 很抱歉没有及时回复你，因为最近在准备博士毕业答辩...如果有问题可以邮件的形式发送。超参数可以参考论文中的设置....
