### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by lichenghui1476529913** [JACKYLUO1991/DCBANet#2]
（1）	在测试DRISHTI_GS数据集的过程中，控制台打印出的平均Dice分数和保存的csv中平均Dice分数计算结果不一样，请问您论文中是根据csv文件中的数据计算的结果吗？
（2）	在进行RIMONE-R3数据集的实验时，用您的网络跑出的效果与您论文中相差也比较大。视盘Dice为0.9384，视杯Dice为0.7924，请问您是对这个数据集做了预处理吗？您能分享一下您使用的RIMONE-R3的数据集吗？

**Comment by frusting** [comment]
请问一下作者，你们的文章和BEAL区别在哪？效果为什么有这么大的提升，特别是RIM数据集上，在两个数据集上的效果都很好？

**Comment by JACKYLUO1991** [comment]
@frusting BEAL的思路是基于域自适应方法，我们的方法针对每个数据集都要训练一次，因此效果更好。
